# Generated by Django 3.2 on 2021-04-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='商品销量'),
        ),
    ]
